### PR TITLE
Improve item insert failure caching performance

### PR DESCRIPTION
**Pull request by Sicryll**
Changed the `CacheFailedInsertInventoryHandler` class to only attempt insert failure optimizations for items which have no NBT tag data. Additionally, the failure optimization path now only evaluates by item type to avoid expensive hash calculations. Computing an aggregate hash of an item stack and its associated NBT data was prohibitively expensive when multiple item stacks being passed in had a variety of NBT data and each failed to insert.

### CODE REVIEW

**Comment by P3pp3rF1y** [comment]
thanks for looking into performance, but have you actually got before and after profiler output? Because the hash is always calculated as part of insert into sophisticated inventories / controller and may be calculcated more than once + there's an additional logic that's run for each insert to figure out where it could fit so I wonder how it is that it would perform better like this - I mean for plain old items with no nbt of course it would but item with nbt will still kill performance if the storage is full unless I am missing anything.

**Comment by Sicryll** [comment]
The problem this is trying to address arises when the destination inventories are all full, in the use case where I encountered this issue there were multiple netherite barrels full of unique armosr drops from mobs. Each had a pipez  item extractor attempting to move I think every item in the source inventory into a destination, for each item this code would then run the hash function twice consuming all of the NBT data, without caching in `ItemStackKey.CACHE`.

Further, so far as I can see the hash would only ever be calculated from `ItemStackKey` when insertion succeeds in the target inventory.

For non-stackable items, in the vast majority of cases they would only ever have extraction attempted once per tick. In the cases where multiple extractions are attempted in the same tick, the performance impact would be negligible compared to the current cost of always generating the hash at least once.

I've attached some profiles including a baseline, single chest blocked with stackable items, single chest blocked with unstackable items, and 4 chests blocked with unstackable items. You can see the exponential cost of this function in the 4 chest profile.

[spark-profiles.zip](https://github.com/P3pp3rF1y/SophisticatedCore/files/13197582/spark-profiles.zip)

**Comment by P3pp3rF1y** [comment]
I am totally confused to be honest, this cache doesn't address extractions at all, it only addresses inserts?

You're right that hash is unnecessarily calculated twice when stack fails to insert definitely something I need to fix, but it is always calculated for any stack, not sure why you would think it only is calculated for successful insert?

I will need some explanation for those profiles - that is which ones are before change and which ones are after. I thought that baseline is before the change and the other ones are after, but in baseline only 0.13% of tick is spent in core code vs the unstackable blocked 4 spends 50% in core code and that appears to be caused by the fact that the cache of failed inserts is skipped and because of that more expensive logic in storageblockentity is called. (Edit: actually now that I am looking at that unstackable one again I can see it's just the hashcode calculation in failed cache, but I still thought that it would show profile after change so that we could compare how it behaves now as I am pretty sure that hashcode still needs to be calculated further in insert logic and probably more than once)

**Comment by Sicryll** [comment]
Sorry just to clarify the profiles are all with the current version of the
code. I figured they should be sufficient to expose the problem and wasn't
in a suitable position to restart the server.

It is only calculated on successful insert because the hash is lazily
evaluated, which would only happen when the stack key is inserted into a
hash container.

If you look again at the 4 chest profile, you will see that the cost is
coming from computing the hash within the caching class, the calls to
insert item are not what is generating the hash and the execution time
there is relatively tiny.

**Comment by Sicryll** [comment]
image

**Comment by P3pp3rF1y** [comment]
so I would need to see profile after the change as well to see that it actually makes any kind of meaningful improvement.
But I still don't understand why you would think that hash is only calculated after successful insert? I can clearly see in cache logic that it checks if the stack was already tried to be inserted in that given tick and hash is also required to do insertion logic in storage blocks / in controller. Why do you feel it is only calculated on successful insertion? And I don't understand what kind of lazy evaluation of hash you are referring to?

**Comment by Sicryll** [comment]
The hash is only calculated when any of the hash containers need to query the hash from `ItemStackKey`, which they will never do if the containers are always empty, which they will be when insertion always fails. `ItemStackKey` only lazily calculates the hash once `hashCode()` is called, so if item insertion always fails then the hash is never required within `wrapped.insertItem`.

Calling `ItemStackKey.getHashCode(stack)` here directly also doesn't populate `ItemStackKey.CACHE` which I mentioned previously, so any successful item insertion will still have to redundantly re-calculate the hash because it's not present in the cache.

In any case, generating this hash value in this code before the inventory attempts to insert guarantees that the hash has to be calculated when it may not be otherwise, which is extremely expensive for items with lots of NBT data.

Again, in this example when each item is unique and unstackable, this failed insert set is not achieving anything because each item only has insertion attempted per inventory a single time. The hash calculation is expensive, so it can be avoided here.

Yes there will still be an underlying problem for items with NBT data and hash generation within insert when at least one insertion does succeed, but this is not the appropriate place to try and solve that issue. However, if at least one insertion is succeeding then it's likely either multiple ticks will follow with no insertions succeeding or that insertions are always succeeding and the total amount of input items queried are vastly fewer because there is no input item buildup due to failed inserts. All of which are vastly preferable situations with existing code versus forcing a hash to be calculated here.

Here is a baseline and bad profile with my fix applied, having 4 netherite barrels blocked and attempting to insert with mostly unique items. The hash function is never necessary when insertion never succeeds.
[fix-spark-profiles.zip](https://github.com/P3pp3rF1y/SophisticatedCore/files/13199331/fix-spark-profiles.zip)

The root cause of this problem really is that he hash function is too expensive for the performance sensitivity of the surrounding code. It would be more practical to have a far cheaper hash function and rely on object comparisons when there is a conflict, rather than putting a lot of effort into the hash and treating it as unique (which would inevitably cause an issue).

**Comment by P3pp3rF1y** [comment]
closing, there's now much more efficient implementation of the caching anyway

**Pull request closed without merging**
