### PR TITLE
Add Advanced Crafting Upgrade to encapsulate refill crafting grid functionality from PR #73

### PR DESCRIPTION
**Pull request by frizzle101101**
there seems to have been an open space for an advanced crafting upgrade. I thought this fit well

dependant pr's:
https://github.com/P3pp3rF1y/SophisticatedStorage/pull/428
https://github.com/P3pp3rF1y/SophisticatedBackpacks/pull/1065

### CODE REVIEW

**Comment by P3pp3rF1y** [comment]
Hey, it would be best to connect on the PR changes before you make actual changes because there are things I want to have different for this feature
- I don't really see a reason for this to be a separate upgrade, it should just be included as an option in default crafting upgrade - it's just a minor QoL on top of what crafting upgrade already does, nothing that justifies a separate upgrade
- I don't really see a reason for switch between where it's refilling from - crafting upgrade today fills items from anywhere in either backpack/storage or player's inventory so refill should do the same and should be a simple on/off switch
- there are a few points on code that I would have but if you can make these 2 changes first I can check on the code again because it's likely that part may change anyway

**Comment by frizzle101101** [comment]
"crafting upgrade today fills items from anywhere in either backpack/storage or player's inventory so refill should do the same and should be a simple on/off switch" - the crafting upgrade as of the pr#73 only does refill from storage. So you dont want to have the option to select refill source, ok thats fine its just less choice for the user, i made the refill source selectable cuz i was already there and i found it useful in gameplay to have the order which is used first storage or inventory selectable...but whatever you want, i just dont like the new meta of filling the crafting grid then balancing it to get multiple items, i just thought it was nice to select the refill from player inventory or storage first.

Justification for second upgrade while minor was oh this is a more advanced crafting feature so make it harder for the user to get kinda like going from the simple crafting table to getting the ae2 system running and getting similar functionality...but if you dont think so it will just make for less additions

**Comment by frizzle101101** [comment]
That all being said if i understand what you want correctly is just:
Basic crafting upgrade with refill option that uses the refill source as storage then player inventory, in that order, with an on off toggle

**Comment by frizzle101101** [comment]
branch moved to https://github.com/FrizMods/SophisticatedCore/tree/1.18.x-AdvancedCraftingUpgrade

**Comment by frizzle101101** [comment]
new pr: https://github.com/P3pp3rF1y/SophisticatedCore/pull/240

**Comment by frizzle101101** [comment]
Hey trying to connect with the team on the changes made in the new PR

**Pull request closed without merging**
